# Generated by Django 5.1.7 on 2026-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_uq_project_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
