# Generated by Django 5.1.7 on 2026-03-04 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('TODO', 'Todo'), ('TOBUY', 'ToBuy'), ('BUDGET', 'Budget')], max_length=16)),
                ('source_id', models.IntegerField()),
                ('kind', models.CharField(choices=[('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue'), ('BUDGET_80', 'Budget 80%'), ('BUDGET_100', 'Budget 100%')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind', 'created_at'], name='idx_reminder_user_kind_ct'), models.Index(fields=['source_type', 'source_id', 'kind'], name='idx_reminder_src_kind')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_type', 'source_id', 'kind', 'due_date'), name='uq_reminder_user_source_kind_due')],
            },
        ),
    ]
