# Generated by Django 5.1.7 on 2026-03-03 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=16)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('RECORDED', 'Recorded'), ('CANCELED', 'Canceled')], default='PLANNED', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('entry_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('linked_tobuy_id', models.UUIDField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='accounts.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'entry_date'], name='idx_ledger_user_date'), models.Index(fields=['user', 'status', 'entry_date'], name='idx_ledger_user_status_date'), models.Index(fields=['user', 'category', 'entry_date'], name='idx_ledger_user_cat_date')],
            },
        ),
    ]
