# Generated by Django 5.1.7 on 2026-03-03 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('IDEA', 'Idea'), ('RESEARCHING', 'Researching'), ('PLANNED', 'Planned'), ('ORDERED', 'Ordered'), ('DELIVERED', 'Delivered'), ('INSTALLED', 'Installed'), ('RETURNED', 'Returned')], default='IDEA', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('preferred_store', models.CharField(blank=True, max_length=200)),
                ('preferred_link', models.URLField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('payer_split_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tobuy_items', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobuy_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'project', 'status', 'target_date'], name='idx_tobuy_usr_prj_st_dt')],
            },
        ),
    ]
