# Generated by Django 5.1.7 on 2026-03-03 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('planning', '0003_tobuyitem_deleted_at_todoitem_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToBuyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('CONSUMED', 'Consumed')], default='ACTIVE', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tobuy_reservations', to='budgets.budgetperiod')),
                ('to_buy_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='planning.tobuyitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobuy_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='idx_tobuy_res_user_st_ct'), models.Index(fields=['budget_period', 'status'], name='idx_tobuy_res_period_st')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ACTIVE')), fields=('to_buy_item',), name='uq_tobuy_active_reservation')],
            },
        ),
    ]
