# Generated by Django 5.1.7 on 2026-03-04 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('planning', '0004_tobuyreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('DELETED', 'Deleted')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_audit_logs', to='budgets.budgetperiod')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='planning.tobuyreservation')),
                ('to_buy_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_audit_logs', to='planning.tobuyitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='idx_res_audit_user_ac_ct'), models.Index(fields=['reservation', 'created_at'], name='idx_res_audit_res_ct')],
            },
        ),
    ]
