# Generated by Django 5.1.7 on 2026-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_reservationauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationauditlog',
            name='action',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('DELETED', 'Deleted'), ('CONSUMED', 'Consumed')], max_length=16),
        ),
    ]
