# Generated by Django 5.1.7 on 2026-03-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_timeblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='block_kind',
            field=models.CharField(choices=[('DEEP_WORK', 'Deep Work'), ('MEETING', 'Meeting'), ('ADMIN', 'Admin'), ('BREAK', 'Break'), ('PERSONAL', 'Personal'), ('GENERAL', 'General')], default='GENERAL', max_length=16),
        ),
    ]
