# Generated by Django 5.1.7 on 2026-03-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_timeblock_block_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
